import { useState, type ReactNode } from 'react';
import { FilePlus, Package, Save } from 'lucide-react';

const API = 'http://localhost:4000/api/templates';

export default function ConfigurationModule() {
  const [template, setTemplate] = useState({ name: '', description: '', content: '' });
  const [pack, setPack] = useState({ name: '', description: '', item: '', price: '' });
  const [message, setMessage] = useState('');
  async function saveTemplate() { const response = await fetch(`${API}/document-templates`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(template) }); if (!response.ok) { setMessage('No se pudo guardar la plantilla'); return; } setTemplate({ name: '', description: '', content: '' }); setMessage('Plantilla guardada'); }
  async function savePackage() { const response = await fetch(`${API}/treatment-packages`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: pack.name, description: pack.description, items: [{ description: pack.item, quantity: 1, unit_price: Number(pack.price) }] }) }); if (!response.ok) { setMessage('No se pudo guardar el paquete'); return; } setPack({ name: '', description: '', item: '', price: '' }); setMessage('Paquete guardado'); }
  return <section className="mx-auto max-w-5xl space-y-6"><div><h2 className="text-2xl font-black text-slate-900">Configuración clínica</h2><p className="mt-1 text-sm text-slate-500">Administra plantillas documentales y tratamientos frecuentes.</p></div>{message && <p className="rounded-xl bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">{message}</p>}<div className="grid gap-5 lg:grid-cols-2"><Panel title="Nueva plantilla documental" icon={<FilePlus className="h-5 w-5" />}><Field label="Nombre" value={template.name} onChange={(value) => setTemplate({ ...template, name: value })} /><Field label="Descripción por defecto" value={template.description} onChange={(value) => setTemplate({ ...template, description: value })} /><TextArea label="Texto base (puede usar {{nombre}}, {{fecha}}, {{dias}})" value={template.content} onChange={(value) => setTemplate({ ...template, content: value })} /><button type="button" onClick={() => void saveTemplate()} className="inline-flex items-center gap-2 rounded-xl bg-teal-600 px-4 py-2.5 text-sm font-bold text-white"><Save className="h-4 w-4" />Guardar plantilla</button></Panel><Panel title="Paquete o tratamiento frecuente" icon={<Package className="h-5 w-5" />}><Field label="Nombre del paquete" value={pack.name} onChange={(value) => setPack({ ...pack, name: value })} /><Field label="Descripción" value={pack.description} onChange={(value) => setPack({ ...pack, description: value })} /><Field label="Ítem incluido" value={pack.item} onChange={(value) => setPack({ ...pack, item: value })} /><Field label="Precio" value={pack.price} onChange={(value) => setPack({ ...pack, price: value })} /><button type="button" onClick={() => void savePackage()} className="inline-flex items-center gap-2 rounded-xl bg-teal-600 px-4 py-2.5 text-sm font-bold text-white"><Save className="h-4 w-4" />Guardar paquete</button></Panel></div></section>;
}
function Panel({ title, icon, children }: { title: string; icon: ReactNode; children: ReactNode }) { return <div className="space-y-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="flex items-center gap-2 font-black text-slate-800">{icon}{title}</h3>{children}</div>; }
function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="block text-xs font-bold text-slate-600">{label}<input value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm font-normal outline-none focus:border-teal-500" /></label>; }
function TextArea({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="block text-xs font-bold text-slate-600">{label}<textarea rows={5} value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 w-full resize-none rounded-lg border border-slate-200 px-3 py-2 text-sm font-normal outline-none focus:border-teal-500" /></label>; }
